// Environment Configuration for SpotifAI - StreamSmart
// This file is automatically generated during AWS Amplify build process
// For local development, create your own version with your API keys

// Fallback configuration for local development
if (typeof window !== 'undefined' && !window.ENV) {
    console.log('🔧 Using local development environment');
    window.ENV = {
        // Add your Gemini API key here for local development
        // GEMINI_API_KEY: 'your_actual_api_key_here'
    };
}