// Environment Configuration for SpotifAI - StreamSmart
// This file is automatically generated during the build process

console.log('🚀 SpotifAI - StreamSmart: Environment configuration loaded');

window.ENV = {
    GEMINI_API_KEY: ''
};

// For debugging (remove in production)
console.log('Environment configured with API key:', window.ENV.GEMINI_API_KEY ? '✅ Present' : '❌ Missing');
